# Generated by Django 5.2.1 on 2025-08-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('monthly', 'Monthly Employee'), ('daily', 'Daily Worker')], default='daily', max_length=10)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('emergency_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_front', models.ImageField(blank=True, null=True, upload_to='aadhar/')),
                ('aadhar_back', models.ImageField(blank=True, null=True, upload_to='aadhar/')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('pf_fund', models.CharField(blank=True, max_length=50, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('esi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('leaves', models.PositiveIntegerField(default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('weekly_off', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('worker_type', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
