# Generated by Django 5.2.1 on 2025-08-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='manager.department'),
            preserve_default=False,
        ),
    ]
