# Generated by Django 5.2.1 on 2025-08-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_permission_role_rolepermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
