# Generated by Django 5.2.1 on 2025-08-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_rename_salary_employee_daily_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='manager.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='manager.designation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='manager.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1223, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='manager.position'),
            preserve_default=False,
        ),
    ]
