# Generated by Django 5.2.1 on 2025-08-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
