# Generated by Django 5.2.1 on 2025-08-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration', models.DurationField(default=0)),
                ('shift_type', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Custom', 'Custom')], default='Day', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
