# Generated by Django 5.2.1 on 2025-08-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.employee')),
                ('shift', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.shift')),
            ],
        ),
    ]
