# Generated by Django 5.2.1 on 2025-08-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_schedule_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Late', 'Late')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
