# Generated by Django 5.2.1 on 2025-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_passbook',
            field=models.ImageField(blank=True, null=True, upload_to='documents/passbook/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='character_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/character_certificate/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='conveyance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='da',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epfo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='esic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='special',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
