# Generated by Django 5.2.1 on 2025-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_employee_bank_passbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='labour_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='professional_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
