# Generated by Django 5.2.1 on 2025-08-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_employee_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], max_length=10)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('half_day_date', models.DateField(blank=True, null=True)),
                ('half_type', models.CharField(blank=True, choices=[('first', 'First Half'), ('second', 'Second Half')], max_length=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superadmin_approval', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('admin_approved_on', models.DateField(blank=True, null=True)),
                ('superadmin_approved_on', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.leave')),
            ],
        ),
    ]
