# Generated by Django 5.2.1 on 2025-08-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='admin_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='superadmin_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(blank=True, choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=20),
        ),
    ]
