# Generated by Django 5.2.1 on 2025-11-24 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_shifttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceSalaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_month', models.DateField(help_text='Month for which advance is requested')),
                ('repayment_method', models.CharField(choices=[('single', 'Single Installment'), ('emi', 'Monthly EMI')], max_length=10)),
                ('emi_months', models.PositiveIntegerField(blank=True, help_text='Applicable only if EMI selected', null=True)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='advance_salary_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superadmin_approval', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('admin_approved_on', models.DateField(blank=True, null=True)),
                ('superadmin_approved_on', models.DateField(blank=True, null=True)),
                ('superadmin_cancelled', models.BooleanField(default=False)),
                ('admin_cancelled', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.employee')),
            ],
        ),
    ]
