# Generated by Django 5.2.1 on 2025-11-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_advancesalaryapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly Salary'), ('daily', 'Daily Wage')], max_length=10)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conveyance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('da', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('esi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('professional_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('labour_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leaves_allowed', models.PositiveIntegerField(default=0)),
                ('weekly_off', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='manager.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('paid_leave_used', models.IntegerField(default=0)),
                ('unpaid_leave', models.IntegerField(default=0)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
