# Generated by Django 5.2.1 on 2025-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_salary_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='loan_deduction_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
